import { fireEvent, render, screen } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { App } from "../../app/App";
import { radiusSearchEstablishment, radiusSearchPage } from "../../test/fixtures";
import { isRadiusSearchPage } from "../../types/api";
import { EMPTY_RADIUS_FORM } from "./radiusTypes";
import { createRadiusSnapshot, validateRadius } from "./radiusUtils";

vi.mock("./RadiusMap", () => ({ RadiusMap: ({ data }: { data: { radiusKm: number; items: unknown[] } }) => <div role="region" aria-label="Mapa da busca por raio">Mapa {data.radiusKm} km · {data.items.length} itens</div> }));
const fetchMock = vi.fn();
const response = (body: unknown, status = 200) => ({ ok: status < 400, status, json: () => Promise.resolve(body) }) as Response;
const catalog = { items: [{ id: "metal", name: "Metal" }] };
beforeEach(() => { fetchMock.mockReset(); fetchMock.mockImplementation((input: RequestInfo | URL) => { const url = input.toString(); if (url.includes("health/live")) return Promise.resolve(response({ status: "ok", service: "sentinel-api" })); if (url.includes("catalog/segments")) return Promise.resolve(response(catalog)); return Promise.resolve(response(radiusSearchPage())); }); vi.stubGlobal("fetch", fetchMock); });

describe("Discovery por raio", () => {
  it("shows a third mode and starts with municipality origin", () => { render(<App />); expect(screen.getByRole("radio", { name: "Por raio" })).toBeInTheDocument(); fireEvent.click(screen.getByRole("radio", { name: "Por raio" })); expect(screen.getByLabelText("Tipo de origem")).toHaveValue("municipality"); expect(screen.getByLabelText("UF da origem")).toBeInTheDocument(); });
  it("validates municipality, coordinate ranges and finite positive radius", () => { expect(validateRadius(EMPTY_RADIUS_FORM)).toMatchObject({ originMunicipioNome: expect.any(String), originUf: expect.any(String), radiusKm: expect.any(String) }); for (const radiusKm of ["0", "-1", "NaN", "Infinity"]) expect(validateRadius({ ...EMPTY_RADIUS_FORM, originMunicipioNome: "SP", originUf: "SP", radiusKm })).toHaveProperty("radiusKm"); expect(validateRadius({ ...EMPTY_RADIUS_FORM, originKind: "coordinates", originLat: "91", originLon: "-181", radiusKm: "1" })).toMatchObject({ originLat: expect.any(String), originLon: expect.any(String) }); });
  it("preserves textual origins and includes only the selected origin", () => { const snapshot = createRadiusSnapshot({ ...EMPTY_RADIUS_FORM, originKind: "cnpj", originCnpj: "00ABC234000155", originCodigoTom: "0001", radiusKm: "5" }); expect(snapshot.origin).toEqual({ kind: "cnpj", cnpj: "00ABC234000155" }); });
  it("calls the radius endpoint with distinct origin and result UFs and renders map/table", async () => { render(<App />); fireEvent.click(screen.getByRole("radio", { name: "Por raio" })); fireEvent.change(screen.getByLabelText("Nome do município"), { target: { value: "SAO PAULO" } }); fireEvent.change(screen.getByLabelText("UF da origem"), { target: { value: "SP" } }); fireEvent.change(screen.getByLabelText("Raio em quilômetros"), { target: { value: "10" } }); fireEvent.change(screen.getByLabelText("UF dos resultados"), { target: { value: "RJ" } }); fireEvent.click(screen.getByRole("button", { name: "Buscar por raio" })); expect(await screen.findByRole("table")).toBeInTheDocument(); const call = fetchMock.mock.calls.find(([input]) => input.toString().includes("/radius/establishments")); const url = new URL(call![0].toString(), "http://local"); expect(url.pathname).toBe("/api/v1/discovery/radius/establishments"); expect(Object.fromEntries(url.searchParams)).toMatchObject({ radius_km: "10", origin_municipio_nome: "SAO PAULO", origin_uf: "SP", uf: "RJ", limit: "50", offset: "0" }); expect(screen.getByRole("region", { name: "Mapa da busca por raio" })).toHaveTextContent("10 km"); });
  it("keeps resolved origin, map and pagination for an empty success", async () => { fetchMock.mockImplementation((input: RequestInfo | URL) => input.toString().includes("radius/establishments") ? Promise.resolve(response(radiusSearchPage([]))) : input.toString().includes("catalog") ? Promise.resolve(response(catalog)) : Promise.resolve(response({ status: "ok", service: "sentinel-api" }))); render(<App />); fireEvent.click(screen.getByRole("radio", { name: "Por raio" })); fireEvent.change(screen.getByLabelText("Nome do município"), { target: { value: "SAO PAULO" } }); fireEvent.change(screen.getByLabelText("UF da origem"), { target: { value: "SP" } }); fireEvent.change(screen.getByLabelText("Raio em quilômetros"), { target: { value: "10" } }); fireEvent.click(screen.getByRole("button", { name: "Buscar por raio" })); expect(await screen.findByText("Nenhum estabelecimento foi encontrado.")).toBeInTheDocument(); expect(screen.getByLabelText("Origem resolvida")).toHaveTextContent("SAO PAULO"); expect(screen.getByRole("region", { name: "Mapa da busca por raio" })).toBeInTheDocument(); expect(screen.getByRole("button", { name: "Anterior" })).toBeDisabled(); });
  it("preserves API order and opens the existing details drawer", async () => { fetchMock.mockImplementation((input: RequestInfo | URL) => input.toString().includes("radius/establishments") ? Promise.resolve(response(radiusSearchPage([radiusSearchEstablishment({ cnpj_full: "002", razao_social: "SEGUNDA" }), radiusSearchEstablishment({ cnpj_full: "001", razao_social: "PRIMEIRA" })]))) : input.toString().includes("catalog") ? Promise.resolve(response(catalog)) : Promise.resolve(response({ status: "ok", service: "sentinel-api" }))); render(<App />); fireEvent.click(screen.getByRole("radio", { name: "Por raio" })); fireEvent.change(screen.getByLabelText("Nome do município"), { target: { value: "SP" } }); fireEvent.change(screen.getByLabelText("UF da origem"), { target: { value: "SP" } }); fireEvent.change(screen.getByLabelText("Raio em quilômetros"), { target: { value: "1" } }); fireEvent.click(screen.getByRole("button", { name: "Buscar por raio" })); await screen.findByRole("table"); const rows = screen.getAllByRole("row").slice(1); expect(rows[0]).toHaveTextContent("SEGUNDA"); expect(rows[1]).toHaveTextContent("PRIMEIRA"); fireEvent.click(screen.getAllByRole("button", { name: "Ver detalhes" })[0]); expect(await screen.findByRole("dialog")).toBeInTheDocument(); });
});

describe("guards de raio", () => {
  it("rejects malformed coordinates, distance, booleans, identifiers and status", () => { const valid = radiusSearchPage(); expect(isRadiusSearchPage(valid)).toBe(true); const item = valid.items[0]; const malformed: unknown[] = [
    { ...valid, origin: { ...valid.origin, latitude: Infinity } },
    { ...valid, items: [{ ...item, distance_km: -1 }] },
    { ...valid, items: [{ ...item, has_geo: 1 }] },
    { ...valid, items: [{ ...item, cnpj_full: 123 }] },
    { ...valid, items: [{ ...item, commercial_status: "CLIENT" }] },
  ]; for (const page of malformed) expect(isRadiusSearchPage(page)).toBe(false); });
});
