import { useEffect, useRef, useState } from "react";
import { SentinelApiError } from "../../services/apiClient";
import { createSavedSearch, deleteSavedSearch, listSavedSearches, type DiscoverySearchSpec, type SavedSearch } from "../../services/sentinelApi";
import { savedSearchKindLabel, toEditableDiscoverySearch, type EditableDiscoverySearch } from "./savedSearches";

const message = (code: string) => ({ saved_search_name_conflict:"Já existe uma pesquisa com esse nome.", saved_search_not_found:"Esta pesquisa já não existe.", database_unavailable:"O banco do Sentinel está indisponível.", request_timeout:"A operação excedeu o tempo limite.", network_error:"Não foi possível conectar à API.", invalid_response:"A API retornou uma resposta inválida." }[code] ?? "Não foi possível concluir a operação.");
export function SavedSearchesPanel({ search, onLoad }: { search: DiscoverySearchSpec | null; onLoad: (editable: EditableDiscoverySearch) => void }) {
 const [open,setOpen]=useState(false),[items,setItems]=useState<SavedSearch[]>([]),[offset,setOffset]=useState(0),[hasMore,setHasMore]=useState(false),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[name,setName]=useState(""),[saveOpen,setSaveOpen]=useState(false),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[confirm,setConfirm]=useState<SavedSearch|null>(null); const controller=useRef<AbortController|null>(null);
 const load=async(next=offset)=>{ controller.current?.abort(); const c=new AbortController(); controller.current=c; setLoading(true); setError(null); try { const page=await listSavedSearches({limit:20,offset:next},{signal:c.signal}); if(!c.signal.aborted){setItems(page.items);setOffset(page.pagination.offset);setHasMore(page.pagination.has_more);} } catch(e){if(!(e instanceof SentinelApiError&&e.code==="request_aborted"))setError(message(e instanceof SentinelApiError?e.code:"network_error"));} finally {if(!c.signal.aborted)setLoading(false);} };
 useEffect(()=>()=>controller.current?.abort(),[]);
 const save=async()=>{const trimmed=name.trim(); if(!search||!trimmed||trimmed.length>120)return; setSaving(true);setError(null);try{await createSavedSearch({name:trimmed,search});setName("");setSaveOpen(false);setNotice("Pesquisa salva.");if(open)void load(0);}catch(e){setError(message(e instanceof SentinelApiError?e.code:"network_error"));}finally{setSaving(false);}};
 const remove=async()=>{if(!confirm)return;setSaving(true);setError(null);try{await deleteSavedSearch(confirm.saved_search_id);setConfirm(null);const next=items.length===1&&offset>0?Math.max(0,offset-20):offset;void load(next);}catch(e){const code=e instanceof SentinelApiError?e.code:"network_error";setConfirm(null);setError(message(code));void load(offset);}finally{setSaving(false);}};
 return <section className="saved-searches" aria-label="Pesquisas salvas"><div className="export-actions__buttons"><button className="secondary-button" type="button" disabled={!search} onClick={()=>{setSaveOpen(true);setError(null);}}>Salvar pesquisa</button><button className="secondary-button" type="button" onClick={()=>{const n=!open;setOpen(n);if(n)void load(0);}}>Pesquisas salvas</button></div>{notice&&<p aria-live="polite">{notice}</p>}{saveOpen&&<div><label htmlFor="saved-search-name">Nome da pesquisa</label><input id="saved-search-name" value={name} maxLength={120} onChange={e=>setName(e.target.value)}/><button type="button" onClick={()=>void save()} disabled={saving||!name.trim()}>Salvar</button><button type="button" onClick={()=>setSaveOpen(false)} disabled={saving}>Cancelar</button></div>}{open&&<div><h2>Pesquisas salvas</h2>{loading&&<p role="status">Carregando pesquisas salvas...</p>}{error&&<p role="alert">{error}</p>}{!loading&&!items.length&&!error&&<p>Nenhuma pesquisa salva.</p>}<ul>{items.map(item=>{const editable=toEditableDiscoverySearch(item.search);return <li key={item.saved_search_id}><strong>{item.name}</strong> — {savedSearchKindLabel[item.search.kind]} {item.search.include_discarded===true&&"(Inclui descartados)"}<br/><small>{new Date(item.created_at).toLocaleString()}</small>{editable?<button type="button" onClick={()=>onLoad(editable)}>Carregar</button>:<p>Esta definição não pode ser carregada nesta versão da interface.</p>}<button type="button" onClick={()=>setConfirm(item)}>Excluir</button></li>;})}</ul><button type="button" onClick={()=>void load(Math.max(0,offset-20))} disabled={loading||offset===0}>Anterior</button><button type="button" onClick={()=>void load(offset+20)} disabled={loading||!hasMore}>Próxima</button>{confirm&&<div role="alertdialog" aria-modal="true"><p>Excluir “{confirm.name}”?</p><button type="button" onClick={()=>void remove()} disabled={saving}>Confirmar exclusão</button><button type="button" onClick={()=>setConfirm(null)} disabled={saving}>Cancelar</button></div>}</div>}</section>;
}
